// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Model;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220108003152_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("test5.Model.Fund", b =>
                {
                    b.Property<int>("fund_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fund_id"), 1L, 1);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fund_id");

                    b.ToTable("Fund");
                });

            modelBuilder.Entity("test5.Model.FundValues", b =>
                {
                    b.Property<int>("fund_id")
                        .HasColumnType("int");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("value_date")
                        .HasColumnType("datetime2");

                    b.HasKey("fund_id");

                    b.ToTable("FundValues");
                });

            modelBuilder.Entity("test5.Model.FundValues", b =>
                {
                    b.HasOne("test5.Model.Fund", "Fund")
                        .WithMany("FundValues")
                        .HasForeignKey("fund_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("test5.Model.Fund", b =>
                {
                    b.Navigation("FundValues");
                });
#pragma warning restore 612, 618
        }
    }
}
